### ISSUE TITLE
Разрешить использовать ключевое слово var для Variable в декларации протокола

### ISSUE THREAD

**Issue by petropavel13** [TouchInstinct/code-quality-ios#20]
Так как `let` мы написать всё равно тут не можем

<img width="849" alt="screen shot 2017-10-25 at 16 21 36" src="https://user-images.githubusercontent.com/6436245/32000852-b586ac74-b9a0-11e7-9436-fcff0aa98f98.png">

```swift
protocol SomeProtocol: class {

    var internalState: Variable<Int> { get }

}
```

**Comment by petropavel13** [comment]
Возможно, так делать не нужно :)

**Comment by igorkislyuk** [comment]
Конечно не нужно. Чтобы удовлетворить этому протоколу, придется делать публичную переменную, что противоречит самому правилу ;)
